### ISSUE TITLE
App request: iWeb

### ISSUE THREAD

**Issue by fancyham** [cormiertyshawn895/Retroactive#117]
No idea how difficult this would be but iWeb would be amazing for so many people who have made and maintained huge websites with the tool over the years.  

It’s still one of the best web site creators out there and it would be so amazing to continue using it.

**Comment by imdamfino** [comment]
I second this request. Having the ability to use iWeb would be great. There are some users I know who have not been upgrading the OS on their systems because of this one app alone.

**Comment by cormiertyshawn895** [comment]
iWeb is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.

You can use Parallels Desktop, VMware Fusion, or UTM to install macOS Mojave and run iWeb’09 there, but because there isn’t OpenGL acceleration, you won’t be able to see live previews, so it’s not very practical.

If you install iWeb’08 on OS X Leopard under Parallels Desktop, VMware Fusion, or UTM, you can open Finder > Applications, right click on the iWeb app and choose "Show Package Contents", then browse to `/Contents/Resources/` and open the `Defaults.plist` in TextEdit.

Find the lines:
```
<key>SFRAcceleratedCanvas</key>
<true/>
```

and change it to:
```
<key>SFRAcceleratedCanvas</key>
<false/>
```

This should get you a usable iWeb’08 with live preview.

**Comment by fancyham** [comment]
Thanks for the tip!
