### ISSUE TITLE
NepTunes support

### ISSUE THREAD

**Issue by onebrownfinch** [cormiertyshawn895/Retroactive#122]
I realize this is probably a pretty niche issue, but I just used Retroactive to get iTunes back on my Mac (thank you so much!) and have found that NepTunes doesn't want to work with iTunes anymore. No idea why this is the case, but hopefully it's fixable. I love NepTunes and would really appreciate the ability to use it with iTunes again!!

**Comment by peterbuga** [comment]
@onebrownfinch i just noticed this problem myself :( 
luckily NepTunes is opensource, I'm not a macos/ios developer but I noticed that Retroactive changes some information related to iTunes when installing it as a results this breaks NepTunes's ability to discover that iTunes is running. I tried some quick files editing but in the best case it might require some NepTunes changes / recompile 

if I find a fix i'll post it here if still interested or for someone else for that matter.

later edit: good news! after some google-ing I managed to quickly change & compile the NepTunes app in order to work with sideloaded iTunes in Big Sur 11.1. PM me if you want this version

**Comment by oskameDEV** [comment]
@peterbuga Unless I'm mistaken Github does not have a messaging system. How can I get my hands on this version of Neptunes you compiled?

**Comment by peterbuga** [comment]
hi @kitsuneDEV 

not sure if this might work but you can give it a try, i hosted my compiled version here https://sharefast.me/4JWX0
because i didn't want to mess around too much this assumes that iTunes is located at `/Applications/iTunes` that's because Music app sort has precedence and the "natural" reference to iTunes doesn't work anymore and i had to hard code it

you might have to Right click -> Open this app 1st time depending on your security settings or even check System Preferences -> Security & Privacy -> General (tab) and see if you can run apps from `Anywhere` (google on how to enable this) sometimes the app shows up here and you have to re-confirm you really want to open it, but then again this is not a sure deal i just made the minimum changes to have it working on my side, I have no idea how to properly compile it for distribution

leave a shout if it works or not, alternatively I could fork the neptunes project and push the changes i've done leaving you with the task to sort out the compilation on your side (if you want to download xcode and fiddle with some project settings)

**Comment by oskameDEV** [comment]
Works like a charm, thanks for this!

I wonder what it took to get it to work, there's another iTunes related app that I love but I can't get to work.

Star Rating https://github.com/MainasuK/Song-Rating

**Comment by peterbuga** [comment]
@kitsuneDEV 
awesome, glad it worked 🙌 !

regarding the "Star Rating" i took a quick peak into the code and it seems to present the same problem/fix as neptunes but the code it's a bit more complex. the good news is that i was able to compile it locally and hopefully with a bit of trial&errors i might be able to get it running too.

is there anyway i might be able to contact you a bit more directly? (to avoid spamming this thread, or maybe move the discussion on Star Rating's issues section)

**Comment by oskameDEV** [comment]
That’s great to hear @peterbuga 
And you’re right about moving our conversation elsewhere.

My email is mail(ä}oska.me

**Comment by peterbuga** [comment]
@kitsuneDEV i've sent you the email a while ago, i hope you got it 🤞

**Comment by oskameDEV** [comment]
I emailed you twice, check your spam folder, though I'v never been told it ends up in there.

**Comment by pedropablopicasso** [comment]
@peterbuga not to spam an old thread but i'd love to know how you got this to work. I'm in desperate need of a working scrobbler with itunes + mac os 12. thanks in advance

**Comment by peterbuga** [comment]
@pedropablopicasso try this [from here](https://wetransfer.com/downloads/82f904fe45df33f2fd261723fc5ae95020220810062846/c915896aeb7d956a55e66ff5b52ab53a20220810062907/1a3636) not sure if it still works or not give it a try
ps: upload expire after 1 week

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
