### ISSUE TITLE
Pro Video Formats 2.1.3 breaks FCP7 in Mojave

### ISSUE THREAD

**Issue by walkinxyz** [cormiertyshawn895/Retroactive#130]
I have verified this on two different machines (MBP 2017 & Mac Pro 2013) with both FCP7 and FCPX installed.

After applying the Pro Video Formats update dated Aug 25, 2020, FCP7 repeatedly throws a codec not found/incompatible hardware error on opening any project.

Otherwise, installing fresh macOS w FCP7 & FCPX resolves the issue, as long as Pro Video Formats update is not applied.

**Comment by leonador2019** [comment]
Is there any other way except installing a fresh new OS?

**Comment by JoHermann** [comment]
Hi all -

I suspect the Apple Pro Video Formats Version 2.1.2 to be the culprit here (@Apple: no offense!). This update is not available anymore and replaced with 2.1.3 with the same date (Aug 25 2020). Judging by the available standalone installers 2.1.1 and 2.1.3 it appears the missing 2.1.2 did in fact delete /Library/QuickTime (possibly amongst other directories) and with that rendered FCP7 useless. So if you have no backup you can resurrect that directory from, I suggest the following process before installing a fresh OS and FCPs:

- download "Pacifist" (http://charlessoft.com - though it works without registration please sincerely consider paying for this nice piece of shareware, I am not affiliated with the creator)
- download Apple Pro Video Formats (2.1.1) via https://support.apple.com/kb/DL2020?locale=en_US
- use Pacifist to open the installer package "ProVideoFormats.pkg" from the ProVideoFormats.dmg
- select "ProVideoFormats.pkg"
- select "Install" from Pacifist's window or ctrl-click and "Install to Default Location"
- confirm installation process with password
- now you should be able to run FCP7 with Retroactive

Details:
Aside other this brings back the /Library/QuickTime directory populated with the Apple standard content. However, if you had other codecs on your machine they need to be reinstalled, too (i.e. Avid Video Codecs, etc.).

With some further testing on my end I can confirm that after following the above laid out process you can now safely install Apple Pro Video Formats 2.1.3 to make sure all other software components are at their latest version.
However, I used the direct download as opposed to the App Store via https://support.apple.com/kb/DL2050?locale=en_US 


Best


Jo

filter Media Postproduction

**Comment by cormiertyshawn895** [comment]
@JoHermann Thank you for writing this up. I've [added a section in README](https://github.com/cormiertyshawn895/Retroactive#final-cut-pro-7-and-the-apple-pro-video-formats-update) to link to your excellent comment and instructions.

**Comment by cormiertyshawn895** [comment]
Thank you again for your feedback. This issue is resolved with Retroactive 1.9 (Build 84) and later. If Retroactive detects the codecs are missing when unlocking Final Cut Pro 7, it will automatically restore them.

Retroactive will also prevent Pro Video Formats from being automatically updated so the problem will not be re-introduced in the future. You can still manually update to newer versions of Pro Video Formats by downloading the installer [from the Apple Support website](https://support.apple.com/downloads/professionalsoftware).

Please [download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases/) and unlock Final Cut Pro 7 again.

**Comment by kanthanpillay** [comment]
Hi all

The good news is that following @JoHermann 's instructions, FCP 7 launches and works on Mojave. 

The bad news is that Retroactive 1.9 **deletes** the folder "/Library/Application Support/Final Cut Pro System Support/Custom Settings". This folder contains all of the ProRes presets.

If I replace this folder from backup, FCP hangs on launch. If I rerun Retroactive, it deletes the folder again.

Anyone else have this problem? Any workaround?
