### ISSUE TITLE
Will Retroactive apps run on Apple Silicon (M1)?

### ISSUE THREAD

**Issue by lukifer** [cormiertyshawn895/Retroactive#149]
I would assume that these apps should work on the new M1 Macs, via Rosetta 2. Has anyone tested them on the pre-release Apple Silicon hardware?

Thanks so much for Retroactive! 😄

**Comment by UInt2048** [comment]
Not pre-release hardware anymore. 😜 

See #161

**Comment by famnva** [comment]
This is the crash report I get when opening iTunes on my MacBook M1:

Process:               iTunes [9451]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [9448]
Responsible:           bash [9448]
User ID:               501

Date/Time:             2020-12-01 20:40:05.869 -0500
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        B09D9942-057A-7119-B7D5-0C69F083FD7D

Sleep/Wake UUID:       EA878515-64E2-4426-8264-366A6EF61DA5

Time Awake Since Boot: 71000 seconds
Time Since Wake:       2700 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x0000000308239ab8   pc: 0x00007ffdffdbc68c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 7948148
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro17,1, BootROM 6723.50.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Sep 11 2020 18:25:33 version 18.20.222.10.7.8.97 FWID 01-17360706
Bluetooth: Version 8.0.1f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0

**Comment by tinbert** [comment]
No problems here with Retroactive 1.9.2 and Aperture, though I had to run Retroactive on Aperture again, after migrating from Catalina.
MacBook Air M1, official macOS 11.0.1

**Comment by famnva** [comment]
With Retrospective 1.9.2, Aperture and iPhoto run fine on my new MacBook Pro with Apple Silicon, i.e, M1 CPU but I get a crash with iTunes.

I upgraded my wife’s MacBook Air, Intel based, to Big Sur and with Retrospective 1.9.2, all three apps run fine. 

Frank

**Comment by RR19840** [comment]
> With Retrospective 1.9.2, Aperture and iPhoto run fine on my new MacBook Pro with Apple Silicon, i.e, M1 CPU but I get a crash with iTunes. I upgraded my wife’s MacBook Air, Intel based, to Big Sur and with Retrospective 1.9.2, all three apps run fine. Frank
> […](#)

same here, iTunes crashes on m1.
worked fine on big sur on my 2015 MacBook pro.

any solution?

**Comment by mrzool** [comment]
iTunes still crashing... that's a bummer 😟

**Comment by ylluminate** [comment]
> iTunes still crashing... that's a bummer 😟

Was this crash with Big Sur or Monterey? Curious if Monterey has improved the situation. I suspect something in the iTunes dependency chain is not running on Rosetta 2 and thus the crash if so... We should somehow try to track down what that dependency might be and if it's possible to force it to run with Rosetta 2.

**Comment by mrzool** [comment]
@ylluminate the crash was on Big Sur. I'm unable to test on Monterey as I didn't upgrade yet.

**Comment by UInt2048** [comment]
@ylluminate Monterey wasn't even announced yet in March 2021.

**Comment by ylluminate** [comment]
I had an interesting experience here as shared here: https://github.com/cormiertyshawn895/Retroactive/issues/255#issuecomment-1013288036 

I migrated an Intel Big Sur installation with iTunes 12.9.5.5 installed and enabled via Retroactive previously. Upon migration (Apple's `Migration Assistant.app`) I found that it STILL works on an Apple Silicon (M1 Max) MacBook Pro with macOS 12.1 (Monterey) fairly well. It doesn't seem to want to connect to iOS devices (with errors), but the old music library is intact and works quite well.

**Comment by Robbiesaviour** [comment]
iTunes seems to run fine, but I haven't managed to get it to sign in as of yet unfortunately. When it starts, a dialog displays stating that an unknown error has occurred (-42408). The app continues to operate, but the Sign In option does nothing when clicked. Gutting, I love iTunes - the Music app is absolutely lousy.
macOS Monterey 12.1 Apple M1 MacBook Pro, 8GB.

**Comment by ylluminate** [comment]
Same here @Robbiesaviour. Music.app sucks nuclear rotten moon cheese. Seriously bad trash. iTunes is working nicely as noted above still even on macOS 12.3ß4, but yes, no sign in stuff.

**Comment by estyseesghosts** [comment]
Haven't tried iTunes but iPhoto works great on my M1 

Tried aperture but I can't get it to open RAWs, just says unsupported file (my camera is old enough that it should load fine and iPhoto takes the same files just fine)

**Comment by k9malinda** [comment]
@estyseesghosts - I can't get iPhoto to run on my M1 - (Big Sur) keeps crashing, how are you getting it to work?

**Comment by dmuiX** [comment]
So sync with iPad and iPhone is definitely not working on M1 in iTunes? If yes this is a real bummer...

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
