### ISSUE TITLE
iTunes on Catalina does not show up in Remote

### ISSUE THREAD

**Issue by llullstudio** [cormiertyshawn895/Retroactive#16]
I am unable to control neither your reinstalled iTunes 12.9.5.5 nor the Catalina-native Music with the "Remote" iOS app. iTunes always complaints that it needs to be given permissions for incoming connections (which I give), to no avail. Is it possible to uninstall iTunes (for diagnostics).

**Comment by cormiertyshawn895** [comment]
>  Is it possible to uninstall iTunes (for diagnostics).

Yes! Just drag the iTunes app to the Trash, and choose "Empty Trash".

---

> I am unable to control neither your reinstalled iTunes 12.9.5.5 nor the Catalina-native Music with the "Remote" iOS app. iTunes always complaints that it needs to be given permissions for incoming connections (which I give), to no avail.

[Many people reported success using iTunes 12.9.5 on macOS Catalina with the iTunes Remote app](https://discussions.apple.com/thread/250716452?page=8) via Retroactive.

![itunes_remote](https://user-images.githubusercontent.com/57056759/68448921-0c3ae880-019a-11ea-8353-d240f806cb74.jpg)
Troubleshooting steps:
- Can you try to pair your Mac with iTunes remote after turning off Firewall on your Mac?  Go to System Preferences > Security & Privacy > Firewall > "Click the lock to make changes." > Turn off Firewall.
- Update iTunes Remote app on your iPhone to the latest version on the App Store.
- On your iPhone, open Remote > Libraries > Edit > (x) to delete the current Library. Instead of using iTunes Home Sharing, try to use "Connect Manually" instead, and enter the 4-digit PIN code on your Mac.

**Comment by alfwatt** [comment]
Remote.app works for me, 100% why I installed iTunes on Catalina!
