### ISSUE TITLE
iMovie 9.0.9

### ISSUE THREAD

**Issue by joni71** [cormiertyshawn895/Retroactive#17]
Hi I'd love to know if there's any plan to add old iMovie 9.0.9 to Retroactive 

Thanks in advance

**Comment by cormiertyshawn895** [comment]
iMovie 9.0.9 is a classic ❤️.

Unfortunately, unlike Aperture and iPhoto, iMovie 9.0.9 is 32-bit only. It will be very difficult to make it work with macOS Catalina.

Are there anything you miss about iMovie 9.0.9 that aren't available in iMovie 10.1.13? Because iMovie 10 is built from the same foundation as Final Cut Pro X, iMovie 10 generally has much better performance and render quality compared to iMovie 9.

**Comment by joni71** [comment]
First of all thanks for your reply .

As music lover i often record live performance and on editing on iMovie 9
I was able to modify the sound with the equalizer included, a feature disappeared on the following iMovie 10 version

Thats why I still use that version , is there any way to use it under Catalina?

Luigi

**Comment by cormiertyshawn895** [comment]
> As music lover i often record live performance and on editing on iMovie 9. 
>
> I was able to modify the sound with the equalizer included, a feature disappeared on the following iMovie 10 version.

Were you referring to the custom Equalizer sliders in iMovie 9 (red)?

<img width="1376" alt="eq" src="https://user-images.githubusercontent.com/57056759/68525709-42a36100-0289-11ea-8a34-4bffc0e2d883.png">

Equalizer presets are still available in iMovie 10, but they are limited to the built-in presets. Are you looking for the custom sliders?

<img width="1392" alt="Screen Shot 2019-11-09 at 12 37 49 AM" src="https://user-images.githubusercontent.com/57056759/68525743-b0e82380-0289-11ea-8b8d-508a2ca0a2f3.png">

> Thats why I still use that version, is there any way to use it under Catalina?

There isn't a way to keep using iMovie 9 on macOS Catalina. The good news is that it is technically possible to add new Equalizer presets to iMovie 10 with your own parameters. 

I can add a new feature to the Retroactive app that lets you add custom Equalizer presets to iMovie 10. It would look like this, which gives you one slider per frequency range like iMovie 9 did. 
<img width="728" alt="Screen Shot 2019-11-09 at 12 57 28 AM" src="https://user-images.githubusercontent.com/57056759/68525980-f86faf00-028b-11ea-99dc-fdb2d2570da6.png">

Then, if you close and re-open iMovie 10, you will be able to find and select your custom Equalizer from the dropdown list of presets.
<img width="1392" alt="Screen Shot 2019-11-09 at 12 59 40 AM" src="https://user-images.githubusercontent.com/57056759/68526019-59978280-028c-11ea-89fd-72cdb6f8e519.png">

This won't be as integrated as iMovie 9 was (because you have to re-launch iMovie to see your new presets), but will this feature be useful for you? If you want this feature, I can try to make this for the next Retroactive update.

**Comment by joni71** [comment]
You can really enable this feature to iMovie 10.1.13 ?

I should me great !!!

Luigi

**Comment by joni71** [comment]
Hi I just dowloaded 1.3 but did’t mention

iMovie 10 EQ …you will do soon ?

Thanks Shawn

**Comment by joni71** [comment]
Hi I just dowloaded 1.3 but did’t mention

iMovie 10 EQ …you will do soon ?

Thanks Shawn

**Comment by joni71** [comment]
Hi I just dowloaded 1.3 but did’t mention

iMovie 10 EQ …you will do soon ?

Thanks Shawn

**Comment by joni71** [comment]
Hi Shawn,

when u think to add " new Equalizer presets to iMovie 10" Feature ?

Luigi

**Comment by joni71** [comment]
Hi Shawn,

do you remember we talked about this in November ....
when u think to add " new Equalizer presets to iMovie 10" Feature ?

Luigi

**Comment by joni71** [comment]
2 years are passed without any response from you

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
