### ISSUE TITLE
Iweb

### ISSUE THREAD

**Issue by zikcollege** [cormiertyshawn895/Retroactive#175]
Hi

Retroactive is a great great app! Thanks a lot!
Can you do the same with iWeb?
Thank you;

**Comment by cormiertyshawn895** [comment]
iWeb is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.

You can use Parallels Desktop, VMware Fusion, or UTM to install macOS Mojave and run iWeb’09 there, but because there isn’t OpenGL acceleration, you won’t be able to see live previews, so it’s not very practical.

If you install iWeb’08 on OS X Leopard under Parallels Desktop, VMware Fusion, or UTM, you can open Finder > Applications, right click on the iWeb app and choose "Show Package Contents", then browse to `/Contents/Resources/` and open the `Defaults.plist` in TextEdit.

Find the lines:
```
<key>SFRAcceleratedCanvas</key>
<true/>
```

and change it to:
```
<key>SFRAcceleratedCanvas</key>
<false/>
```

This should get you a usable iWeb’08 with live preview.
