### ISSUE TITLE
Learn what to do if iTunes can't be downloaded due to limited internet connectivity

### ISSUE THREAD

**Issue by abelpinate** [cormiertyshawn895/Retroactive#18]
In my case, I have tried severals time to get it downloaded in my Mac and always goes down.
I have locally the 12.8.2 and I can't used it.

It would be great to obtain the link to download the dmg itself, or whatever uses the app in the download to get it in advance. My connection country it's very limited (1,5mb) and the apps problems get things worse.

**Comment by cormiertyshawn895** [comment]
If you have limited bandwidth, try to download and install iTunes 12.6.5 instead. It's much smaller and quicker to download.

Let me know if it works for you!

**Comment by abelpinate** [comment]
Hello!

Well, right now it’s a 55% in 12.9, I don’t know the down speed… but as far I can see, the app don’t get the total bandwidth because I can see it.

I have noted the app when it’s downloading, don’t allows the screen to turn off. I’m not talking in sleep mode, just the screen turned off.

I really want to try this. I don’t like at all Music.

Really, there’s no way to download the 12.9.5 to get in the hard drive for future installations? I placed the 12.8.2 in the app folder and didn’t take it.

Thank you very much for all the effort.

**Comment by cormiertyshawn895** [comment]
If you are very determined to pre-download iTunes 12.9.5, there is a workaround.

1. Quit Retroactive.
1. [Download this pkg file](http://swcdn.apple.com/content/downloads/17/32/061-26589-A_8GJTCGY9PC/25fhcu905eta7wau7aoafu8rvdm7k1j4el/InstallESDDmg.pkg).
1. Finder > Go > "Go to folder".
1. In the text field, enter `/tmp`, and click Go.
1. If there is already a InstallESDDmg.pkg in this `/tmp` folder, drag it to the trash to delete it.
1. Copy your downloaded InstallESDDmg.pkg to this `/tmp` folder. Don't rename it. Make sure it's directly copied to `/tmp` itself, not a subfolder under `/tmp`.
1. Open Retroactive again, iTunes > iTunes 12.9.5 > Continue.
1. When Retroactive says "Downloading iTunes", the progress value will be at 0% for half a minute, but the progress bar will move forward. This is normal. Instead of downloading iTunes, Retroactive is verifying your local InstallESDDmg.pkg.
1. Retroactive should be able to install iTunes 12.9.5 with your local installer.

See if this works!

**Comment by abelpinate** [comment]
Hi!

Sorry, it was late. I needed go to bed. But I’m happy. It worked. When I woke up, the process was waiting for me to continue. Thanks I zipped the iTunes library before install Catalina.

As far I could understand, what your app do, it’s download Mojave, unzip and extract the iTunes app. I was asking for the file, because I’m planning to do a fresh install.

In fact, I have to more questions: 
Since I keep a backup from the early OS (in this case Mojave), 

1 there’s a way to help Retroactive’s process keeping the extracted folder with the iTunes app and any other file (those you considere necessary for the process) and trash the InstallESDDmg pkg? 
The pkg and extracted folder were there this morning. I made a backup of both just before I read you mail.

2 You can install the 12.9 and 12.6 at the same time? 
I needed the 12.9 because my library it was last saved with this one… you know iTunes didn’t let you open newer on older. But I have and iDevice with iOS 9.3.6. For my country problems, I haven’t had the opportunity to get a new one and get apps on it, it’s a workaround very large (going to the iTunes store, purchasing the app, going to the device, tapping the cloud, you know) and I do this with a virtual machine. I mean, 15gb spend just to download older apps.

Horrible.

I’m in Venezuela. My country it’s limited to 1,5mbs per second by the way. So it’s very slow. 
It’s horrible… x2

HAHAHAHA

Anyway… thank you very mucho for this thing! You have made my day!

Regards,
Abel

**Comment by cormiertyshawn895** [comment]
> Anyway… thank you very mucho for this thing! You have made my day!

Super happy to help!

---

> 1 there’s a way to help Retroactive’s process keeping the extracted folder with the iTunes app and any other file (those you considere necessary for the process) and trash the InstallESDDmg pkg?
The pkg and extracted folder were there this morning. I made a backup of both just before I read you mail.

The iTunes app modified and installed by Retroactive is standalone, which means it can be copied to another Mac or a new macOS installation on the same Mac. You just need to copy `/Application/iTunes.app` to a backup drive or volume, then copy it back to `/Applications` after re-installing macOS. 

There's no need to run Retroactive again if the `iTunes.app` you copied to `/Applications` was previously installed and modified by Retroactive.

---

> 2 You can install the 12.9 and 12.6 at the same time?
> I needed the 12.9 because my library it was last saved with this one… you know iTunes didn’t let you open newer on older. But I have and iDevice with iOS 9.3.6. For my country problems, I haven’t had the opportunity to get a new one and get apps on it, it’s a workaround very large (going to the iTunes store, purchasing the app, going to the device, tapping the cloud, you know) and I do this with a virtual machine. I mean, 15gb spend just to download older apps.

I completely understand this! Yes, you can install iTunes 12.9 and iTunes 12.6 at the same time with this workaround (Step 3 to 6 is only necessary if you have limited internet connectivity):
1. Quit Retroactive.
1. Rename `iTunes.app` (Version 12.9.5) in /Applications into `iTunes 12.9.5.app` (or any name that isn't `iTunes.app`).
1. [Download the pkg file for iTunes 12.6.5](https://secure-appldnld.apple.com/itunes12/091-87821-20180912-69177170-B085-11E8-B6AB-C1D03409AD2A/iTunes12.6.5.dmg).
1. Finder > Go > "Go to folder". In the text field, enter `/tmp`, and click Go.
1. If there is already a iTunes12.6.5.dmg in this `/tmp` folder, drag it to the trash to delete it.
1. Copy your downloaded iTunes12.6.5.dmg to this `/tmp` folder. Don't rename it. Make sure it's directly copied to `/tmp` itself, not a subfolder under `/tmp`.
1. Open Retroactive again, iTunes > iTunes 12.6.5 > Continue.
1. Instead of downloading iTunes 12.6.5, Retroactive will use your local iTunes12.6.5.dmg.
1. Retroactive will install iTunes 12.6.5 in /Applications, and it will exist alongside with iTunes 12.9.5.

---

Making sure iTunes 12.9.5 co-exists with iTunes 12.6.5:
1. Before launching iTunes 12.6.5, hold down the option key, and choose to create a new iTunes Library, or open a compatible iTunes Library.
1. Before launching iTunes 12.9.5, hold down the option key, and choose your latest iTunes library.
1. **You must not rename `iTunes.app` (Version 12.6.5). iTunes 12.6.5 will crash if its name is not exactly `iTunes.app` (This is important).**
1. You can rename `iTunes.app` (Version 12.9.5) into anything else. This is how you can get them to co-exist.

---

If you launched iTunes 12.9.5 without manually choosing the latest iTunes library, it will automatically upgrade your iTunes 12.6.5 library, which makes it incompatible with iTunes 12.6.5. To launch iTunes 12.6.5 again:
1. Open Finder, locate the newly upgraded iTunes library folder > Previous iTunes Libraries.
1. Copy `iTunes Library [Year-month-date].itl` to the main iTunes library folder. 
1. Delete `iTunes Library.itl` from the main iTunes library folder.
1. Rename `iTunes Library [Year-month-date].itl` into `iTunes Library.itl`.
1. Launch iTunes 12.6.5.

**Comment by abelpinate** [comment]
Thank you very very much for this kind explanation.

Very clear all. I have had downloaded the 12.6.5 in the past, but wasn’t unable to install again and start to use the virtual machine as I said before.

But so good to know it’s a standalone that you can use in any future.
I start to think that it’s not good that resistance to change. I’m sure in any future, Apple will change all and maybe in a few years likes had happened with PPC to intel, we need to change all the workaround… but a that time, I hope we have again a proper app.

I will try the dual iTunes option. I have a library just with the apps, there’s no music. Just change name, and select it.

The only bug, by far it’s if you’re changing tags in 12.9.5, and appears the windows with the progression bar. Says “message”… something that I didn’t see before… but it’s not important. Just if you want to add to the app’s features.

Thank you very much! For real

Regards,
Abel
