### ISSUE TITLE
Unable to get iTunes to work. Giving error before opening.

### ISSUE THREAD

**Issue by brad992** [cormiertyshawn895/Retroactive#187]
I just tried Retroactive for the first time and I can't get iTunes to work. I've gone through the install process, which was fine, then tried opening it after that but it just gives a big error. I'm using a 2 week new m1 macbook air lol. 

ERROR MESSAGE BELOW

```
Process:               iTunes [30043]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [30040]
Responsible:           bash [30040]
User ID:               502

Date/Time:             2021-01-09 02:08:49.492 +0800
OS Version:            macOS 11.0.1 (20B29)
Report Version:        12
Anonymous UUID:        08B17F71-F6D2-449C-3927-9A98B32B2297

Sleep/Wake UUID:       AF30A7A9-549A-422B-B0F9-EEFF8C6165C3

Time Awake Since Boot: 180000 seconds
Time Since Wake:       6200 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x0000000310506a50   pc: 0x00007ffdffeab68c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 184760
    thread_create: 0
    thread_set_state: 0

Model: MacBookAir10,1, BootROM 6723.50.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Sep 11 2020 18:25:33 version 18.20.222.10.7.8.97 FWID 01-17360706
Bluetooth: Version 8.0.1f5, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Air, Apple Inc., 0.0
Thunderbolt Bus: MacBook Air, Apple Inc., 0.0

```

**Comment by dylanhoppe2003** [comment]
Same issue, on M1 MacBook Pro.
`
Process:               iTunes [1323]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [1320]
Responsible:           bash [1320]
User ID:               501

Date/Time:             2021-01-13 23:41:59.829 -0500
OS Version:            macOS 11.1 (20C69)
Report Version:        12
Anonymous UUID:        BA3B5ABD-F9CF-54D3-3C55-B1782FC90708


Time Awake Since Boot: 1300 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000030bd13aa8   pc: 0x00007ffdffc2346c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1044
    thread_create: 0
    thread_set_state: 0

Model: MacBookPro17,1, BootROM 6723.61.3, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Oct 20 2020 12:49:54 version 18.20.222.14.7.8.100 FWID 01-ba327c2d
Bluetooth: Version 8.0.2f9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0
Thunderbolt Bus: MacBook Pro, Apple Inc., 0.0
`

**Comment by SwissmonBeat** [comment]
Namespace CODESIGNING, Code 0x1

It's a sign problem. I tried to manually sign the app but unfortunatly it's not working...

Maybe someone will figure something

**Comment by eismann23** [comment]
Anyone have any news on this?

**Comment by clayton-grey** [comment]
Same. M1. Tried to remove the signature as described in the deep-dive link, but also no dice. Sad to see there's no solution for this.

Trying the solution here:

https://github.com/cormiertyshawn895/Retroactive/issues/14

I am getting a new error:

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries, ignoring DYLD_* env vars
@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib

Dyld Error Message:
  dyld: Using shared cache: 1C99695B-39A1-3CF1-BCD1-AB8BF015FD98
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
  Referenced from: /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
  Reason: unsafe use of @executable_path in /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes with restricted binary (Codesign main executable with Library Validation to allow @ paths)
  
```

Installing Xcode, as the user in that other thread, and unfortunately, I'm getting the same error as I did before installing Xcode. (Re-ran Retroactive as well before running it again, just to be sure.)

**Comment by SwissmonBeat** [comment]
Yup, now there is an issue about the dyld library. I'm having the same error. Again, the app won't open because of security issue. Unfortunately it's the deepest I've been. I even try to look at the code of Retroactive on Xcode but sadly I didn't find anything. I will give a better look asap. Since then, you could still use iTunes 12.6...

**Comment by clayton-grey** [comment]
I have tried 12.6.5 - on the plus side it opens. BUT it gives a number of errors and cannot load the store. If there's anyway to get around the linking error, that would be ace, if the application will otherwise behave normally.

**Comment by hirokoby** [comment]
I'm getting similar error on my M1 MacBook Air.

**Comment by ErKiran** [comment]
Getting Similar error on my MacBook Air M1.

**Comment by SwissmonBeat** [comment]
Is anyone knows how to codesign an app ? aha, or how to force to use a dyld library ? Or how to use Xcode and see if there is someting we could change in the Retroactive app ? The app download the .pkg of iTunes on internet, then create an app with iTunes in it (like an inception). So maybe if we look throught the code of Retroactive we may find something.

**Comment by clayton-grey** [comment]
Codesigning itself isn't the issue so much as what seems to be a general change to the way the OS allows dynamically linked libraries within applications - by their very nature a dynamically linked code library presents an opportunity to a potential security intrusion, and it would seem Apples attempts at producing "security" in the form of locking the OS down involve changes to the ways libraries are integrated. I'm not an OS X developer though, so I haven't read their documentation on the subject, but it seems pretty easy to read between the lines here.

There may be some way to force permission, but it also seems that Apple is actively looking for ways to prevent people from doing things like this, so it also presents more opportunities for this to break again with a future OS update.

I still welcome insight from someone who is better informed on the specifics, if there is a way to wrap things up in a compliant way, that would be rad. In the meantime, I guess I'll just keep using it on Windows? What a weird turn of events.

**Comment by kirb** [comment]
I managed to fix the issue with iTunes 12.9. iTunes was using `@rpath` for libgnsdk (Gracenote SDK I guess), but rpath is considered dangerous, so nowadays its use is discouraged. macOS on Apple Silicon seems to take the discouragement a step further by not allowing rpaths to be used at all, even under Rosetta. This can be fixed by using `@executable_path`, which Apple should have done in the first place, and they now do with Music.app.

I don’t have the exact commands I used on-hand, but it was likely something like:

```bash
# Fix the Gracenote SDK load commands
cd /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents
for i in manager dsp musicid submit; do
	install_name_tool -change @rpath/libgnsdk_${i}.3.06.1.dylib @executable_path/../Frameworks/libgnsdk_${i}.3.06.1.dylib MacOS/iTunes
done

for i in dsp musicid submit; do
	install_name_tool -change @rpath/libgnsdk_manager.3.06.1.dylib @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib Frameworks/libgnsdk_${i}.3.06.1.dylib
done

# Re-sign iTunes
codesign -s - --deep --force /Applications/iTunes.app
```

Opening iTunes throws up an alert saying “An unknown error occurred (-42408).” but after clicking OK, the library features seem to work. I can’t get past the welcome screens for the Store or Apple Music, the Continue button does nothing when clicked.

My problem now is that permissions don’t seem to work, so iTunes doesn’t see my iPod, and can’t access the music library stored on my NAS (accessing network volumes is usually meant to trigger a permission prompt). The Privacy pane crashes when I add iTunes.app to Full Disk Access! This *may* be fixed by codesigning with a Developer ID certificate, I haven’t tried this yet, but clearly that’s not ideal because it requires a paid Apple developer account.

Perhaps this output in terminal may have something to do with it:

```
2021-03-30 10:48:16.827 failed to create BKAgent: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.BKAgentService" UserInfo={NSDebugDescription=connection to service on pid 0 named com.apple.BKAgentService}
```

It‘s the only suspect-looking line different from the ones seen when I run Music directly from terminal.

**Comment by clayton-grey** [comment]
That sounds very similar to the behavior I'm getting with 12.6.5. (I'm not trying to sync a device, so I'm not sure how that behaves.) As noted above, the library looks "normal" but there are a number of error code pop-ups, and the store doesn't work at all.

A quick search seems to relate com.apple.BKAgentService to Books, but if that is an error related to changes to the Books application, then it seems like people who aren't on M1's might get an error there as well? I don't see any other tickets related to the store not loading or Books. Or maybe the error is also quietly happening for them, but it's not of concern?

The closest errors in that numeric range I can spot in Apple's support are both related to the iTunes Store though:
https://support.apple.com/en-us/HT204649

There is an older troubleshooting page I spotted for this specific error code (also showing the older more verbose error window):

https://www.tenorshare.com/fix-itunes/how-to-fix-itunes-error-42408.html

@kirb, do any of their suggested remedies seem to do anything?

**Comment by kirb** [comment]
Based on Console.app output, I think the issue is that now iTunes is no longer signed by an Apple cert. This all works fine on my Intel Mac because iTunes.app doesn’t get patched or resigned:

```bash
# Intel
$ codesign -dvv /Applications/iTunes.app/Contents/MacOS/iTunes.app 2>&1 | grep -i apple
Identifier=com.apple.iTunes
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA

# ARM
$ codesign -dvv /Applications/iTunes.app/Contents/MacOS/iTunes.app 2>&1 | grep -i apple
Identifier=com.apple.iTunes
```

The offending console output looks like:


<details>
<summary>Console output</summary>

```
14:28:51.194066+1030	accountsd	AccountsDaemon	"<private> (<private>) received"
14:28:51.196064+1030	accountsd	AccountsDaemon	"Cannot check access to a private account type: <private>"
14:28:51.196093+1030	accountsd	AccountsDaemon	"No TCC state found: <private>, <private>"
14:28:51.196528+1030	accountsd	AccountsDaemon	"Client <private> is not allowed to access accounts of type <private>."
14:28:51.196562+1030	accountsd	AccountsDaemon	Unentitled access by client 'iTunes' (selector: <private>)
14:28:51.196754+1030	iTunes	Accounts	"Error returned from daemon: Error Domain=com.apple.accounts Code=9 "(null)""
14:28:51.196907+1030	iTunes	AppleMediaServices	ACAccountStore: Failed to fetch the iTunes accounts. error = Error Domain=com.apple.accounts Code=9 "(null)"
14:28:51.197688+1030	accountsd	AccountsDaemon	"Cannot check access to a private account type: <private>"
14:28:51.197712+1030	accountsd	AccountsDaemon	"No TCC state found: <private>, <private>"
14:28:51.197832+1030	accountsd	AccountsDaemon	"Client <private> is not allowed to access accounts of type <private>."
14:28:51.197858+1030	accountsd	AccountsDaemon	Unentitled access by client 'iTunes' (selector: <private>)
14:28:51.198076+1030	iTunes	Accounts	"Error returned from daemon: Error Domain=com.apple.accounts Code=9 "(null)""
14:28:51.198343+1030	iTunes	AppleMediaServices	ACAccountStore: [0728E93F] Failed to create/fetch the local account. error = Error Domain=com.apple.accounts Code=9 "(null)"
14:28:51.199115+1030	iTunes	AppleMediaServices	AMSAcknowledgePrivacyTask: [0728E93F] === Starting ===
14:28:51.199234+1030	iTunes	AppleMediaServices	AMSKeepAlive: [0728E93F] Starting keep alive: com.apple.AppleMediaServices.AMSAcknowledgePrivacyTask-3
14:28:51.199368+1030	iTunes	AppleMediaServices	AMSAcknowledgePrivacyTask: [0728E93F] Running AMSAcknowledgePrivacyTask. privacyIdentifiers = {(
    "com.apple.onboarding.itunesstore"
)}
14:28:51.200241+1030	accountsd	AccountsDaemon	"Cannot check access to a private account type: <private>"
14:28:51.200272+1030	accountsd	AccountsDaemon	"No TCC state found: <private>, <private>"
14:28:51.200555+1030	iTunes	Accounts	"Error returned from daemon: Error Domain=com.apple.accounts Code=9 "(null)""
14:28:51.200407+1030	accountsd	AccountsDaemon	"Client <private> is not allowed to access accounts of type <private>."
14:28:51.200436+1030	accountsd	AccountsDaemon	Unentitled access by client 'iTunes' (selector: <private>)
14:28:51.200697+1030	iTunes	AppleMediaServices	ACAccountStore: Failed to fetch the iTunes accounts. error = Error Domain=com.apple.accounts Code=9 "(null)"
14:28:51.200680+1030	accountsd	AccountsDaemon	"Cannot check access to a private account type: <private>"
14:28:51.200710+1030	accountsd	AccountsDaemon	"No TCC state found: <private>, <private>"
14:28:51.200999+1030	iTunes	Accounts	"Error returned from daemon: Error Domain=com.apple.accounts Code=9 "(null)""
14:28:51.200855+1030	accountsd	AccountsDaemon	"Client <private> is not allowed to access accounts of type <private>."
14:28:51.200887+1030	accountsd	AccountsDaemon	Unentitled access by client 'iTunes' (selector: <private>)
14:28:51.201137+1030	iTunes	AppleMediaServices	ACAccountStore: [0728E93F] Failed to create/fetch the local account. error = Error Domain=com.apple.accounts Code=9 "(null)"
14:28:51.201215+1030	iTunes	AppleMediaServices	AMSAcknowledgePrivacyTask: [0728E93F] == Finished ===
14:28:51.201309+1030	iTunes	AppleMediaServices	AMSKeepAlive: [0728E93F] Releasing
14:28:51.201626+1030	accountsd	AccountsDaemon	"Cannot check access to a private account type: <private>"
14:28:51.201652+1030	accountsd	AccountsDaemon	"No TCC state found: <private>, <private>"
14:28:51.201783+1030	accountsd	AccountsDaemon	"Client <private> is not allowed to access accounts of type <private>."
14:28:51.201808+1030	accountsd	AccountsDaemon	Unentitled access by client 'iTunes' (selector: <private>)
14:28:51.201917+1030	iTunes	Accounts	"Error returned from daemon: Error Domain=com.apple.accounts Code=9 "(null)""
14:28:51.202054+1030	iTunes	AppleMediaServices	ACAccountStore: [0728E93F] Failed to create/fetch the local account. error = Error Domain=com.apple.accounts Code=9 "(null)"
14:28:51.202100+1030	iTunes	AppleMediaServices	AMSAcknowledgePrivacyTask: [0728E93F] Determining if privacy acknowledgement is needed. privacyIdentifier = com.apple.onboarding.itunesstore
14:28:51.202208+1030	iTunes	AppleMediaServices	AMSAcknowledgePrivacyTask: [0728E93F] No account provided, attempting to use the local account. privacyIdentifier = com.apple.onboarding.itunesstore
14:28:51.202943+1030	accountsd	AccountsDaemon	"Cannot check access to a private account type: <private>"
14:28:51.202966+1030	accountsd	AccountsDaemon	"No TCC state found: <private>, <private>"
14:28:51.203075+1030	accountsd	AccountsDaemon	"Client <private> is not allowed to access accounts of type <private>."
14:28:51.203099+1030	accountsd	AccountsDaemon	Unentitled access by client 'iTunes' (selector: <private>)
14:28:51.203203+1030	iTunes	Accounts	"Error returned from daemon: Error Domain=com.apple.accounts Code=9 "(null)""
14:28:51.203341+1030	iTunes	AppleMediaServices	ACAccountStore: [0728E93F] Failed to create/fetch the local account. error = Error Domain=com.apple.accounts Code=9 "(null)"
14:28:51.203383+1030	iTunes	AppleMediaServices	AMSAcknowledgePrivacyTask: [0728E93F] Privacy acknowledgement is needed because we failed to get an account.
14:28:51.211390+1030	iTunes	OnBoardingKit	presentation of about event: gdprLinkShown identifier: <private>
14:28:51.211463+1030	iTunes	CoreAnalytics	Dropping gdprLinkShown as it isn't used in any transform (not in the config or budgeted?)
```

</details>

The entitlements in the iTunes binary look like this:

<details>
<summary>iTunes.app entitlements</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.PairingManager.Read</key>
	<true/>
	<key>com.apple.PairingManager.RemovePeer</key>
	<true/>
	<key>com.apple.PairingManager.Write</key>
	<true/>
	<key>com.apple.application-identifier</key>
	<string>com.apple.iTunes</string>
	<key>com.apple.authkit.client.internal</key>
	<true/>
	<key>com.apple.avfoundation.allow-system-wide-context</key>
	<true/>
	<key>com.apple.avfoundation.allows-access-to-device-list</key>
	<true/>
	<key>com.apple.avfoundation.allows-set-output-device</key>
	<true/>
	<key>com.apple.cdp.recoverykey</key>
	<true/>
	<key>com.apple.mediaremote.allow</key>
	<array>
		<string>TVPairing</string>
	</array>
	<key>com.apple.private.DeviceSupportUpdater.requestor</key>
	<true/>
	<key>com.apple.private.accounts.allaccounts</key>
	<true/>
	<key>com.apple.private.aps-connection-initiate</key>
	<true/>
	<key>com.apple.private.audio.notification-wake-audio</key>
	<true/>
	<key>com.apple.private.bmk.allow</key>
	<true/>
	<key>com.apple.private.commerce</key>
	<array>
		<string>Accounts</string>
	</array>
	<key>com.apple.private.fpsd.client</key>
	<true/>
	<key>com.apple.private.notificationcenter-system</key>
	<array>
		<dict>
			<key>identifier</key>
			<string>com.apple.appstoreagent</string>
		</dict>
	</array>
	<key>com.apple.private.rtcreportingd</key>
	<true/>
	<key>com.apple.private.security.storage.mobilesync.heritable</key>
	<true/>
	<key>com.apple.private.sqlite.sqlite-encryption</key>
	<true/>
	<key>com.apple.private.tcc.allow</key>
	<array>
		<string>kTCCServiceAddressBook</string>
		<string>kTCCServicePhotos</string>
		<string>kTCCServiceAppleEvents</string>
	</array>
	<key>keychain-access-groups</key>
	<array>
		<string>com.apple.pairing</string>
		<string>com.apple.airplay</string>
	</array>
</dict>
</plist>
```

</details>

I’m not too sure how this can be fixed, short of booting with boot-arg `amfi_get_out_of_my_way=1`, which is super dangerous and absolutely not recommended.

Not being able to access my network share was my mistake, I removed bash from Full Disk Access not realising that was put there by Retroactive. Works now that I added it back. It can see my iPod Classic and iPhone 12, but both trigger a message:

> iTunes cannot read the contents of the iPod “iPod”. Go to the Summary tab in iPod preferences and click Restore to restore this iPod to factory settings.

The iPhone sort of makes sense <del>either because it’s 2-3 years newer than this iTunes build or</del> because it’s relying on the pairing entitlements that are being refused due to ad-hoc signing. I can’t understand the iPod though as I was pretty sure that works entirely via disk access. (Edit: iPhone shows up perfectly on Intel, with icons and model name, since that stuff is handled by the macOS built-in MobileDevice.framework.)

Edit: Reproduced the same behavior on Intel by resigning iTunes with a Developer ID cert (it was refusing to launch with relative `@rpath` or `@executable_path` under ad-hoc signing - odd that’s not an issue under Rosetta!). So it’s definitely behavior caused by it no longer getting entitlements since it’s not signed by Apple.

**Comment by SwissmonBeat** [comment]
> I managed to fix the issue with iTunes 12.9. iTunes was using `@rpath` for libgnsdk (Gracenote SDK I guess), but rpath is considered dangerous, so nowadays its use is discouraged. macOS on Apple Silicon seems to take the discouragement a step further by not allowing rpaths to be used at all, even under Rosetta. This can be fixed by using `@executable_path`, which Apple should have done in the first place, and they now do with Music.app.
> 
> I don’t have the exact commands I used on-hand, but it was likely something like:
> 
> ```shell
> # Fix the Gracenote SDK load commands
> cd /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents
> for i in manager dsp musicid submit; do
> 	install_name_tool -change @rpath/libgnsdk_${i}.3.06.1.dylib @executable_path/../Frameworks/libgnsdk_${i}.3.06.1.dylib MacOS/iTunes
> done
> 
> for i in dsp musicid submit; do
> 	install_name_tool -change @rpath/libgnsdk_manager.3.06.1.dylib @executable_path/../Frameworks/libgnsdk_manager.3.06.1.dylib Frameworks/libgnsdk_${i}.3.06.1.dylib
> done
> 
> # Re-sign iTunes
> codesign -s - --deep --force /Applications/iTunes.app
> ```
> 
> Opening iTunes throws up an alert saying “An unknown error occurred (-42408).” but after clicking OK, the library features seem to work. I can’t get past the welcome screens for the Store or Apple Music, the Continue button does nothing when clicked.
> 
> My problem now is that permissions don’t seem to work, so iTunes doesn’t see my iPod, and can’t access the music library stored on my NAS (accessing network volumes is usually meant to trigger a permission prompt). The Privacy pane crashes when I add iTunes.app to Full Disk Access! This _may_ be fixed by codesigning with a Developer ID certificate, I haven’t tried this yet, but clearly that’s not ideal because it requires a paid Apple developer account.
> 
> Perhaps this output in terminal may have something to do with it:
> 
> ```
> 2021-03-30 10:48:16.827 failed to create BKAgent: Error Domain=NSCocoaErrorDomain Code=4097 "connection to service on pid 0 named com.apple.BKAgentService" UserInfo={NSDebugDescription=connection to service on pid 0 named com.apple.BKAgentService}
> ```
> 
> It‘s the only suspect-looking line different from the ones seen when I run Music directly from terminal.

Hi mate, thank you for your help. However I can't achieve what you did. I tried the command you gave but unfortunatly it's not working. Maybe I'm mising something? Could you provide more details about how you did it? Thank you again!

**Comment by StevenRCE0** [comment]
I've tried code signing with ```-o library```, and iTunes launches fine, but there goes error -42408, showing an empty library. 
I guess there's more stuff to fix about code signing and entitlements, but I weren't able to figure it out...

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

**Comment by kristibektashi** [comment]
> Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.
> 
> If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

On Apple Silicon Macs you could also offer to install iTunes 12.8.3.1 since it's the newest version that works without disabling SIP
