### ISSUE TITLE
Aperture crash

### ISSUE THREAD

**Issue by Code-DJ** [cormiertyshawn895/Retroactive#2]
Hi @cormiertyshawn895 I ran the tool and applied the fix for Aperture but when I launch it, it crashes.

Under the report it shows the following:

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer
  Referenced from: /Applications/Aperture.app/Contents/MacOS/Aperture
  Reason: no suitable image found.  Did find:
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: open() failed with errno=13
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: stat() failed with errno=1
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: open() failed with errno=13
	/Applications/Aperture.app/Contents/MacOS/../Frameworks/ApertureFixer.framework/Versions/A/ApertureFixer: stat() failed with errno=13
```

**Comment by cormiertyshawn895** [comment]
This is very strange. Retroactive was probably damaged during download or during ZIP archive expansion. 

Did you use a third party app (such as Keka or BetterZip) instead of the built-in Archive Utility in macOS to expand the downloaded zip?

Things to try:
1. [Restore Archive Utility as the default application to expand ZIP archives](https://forum.keka.io/viewtopic.php?t=2092)
1. [Re-download Retroactive from the Release page](https://github.com/cormiertyshawn895/Retroactive/releases)
1. Launch Retroactive, select Aperture, and choose "Modify Aperture again"
<img width="1123" alt="run_again" src="https://user-images.githubusercontent.com/57056759/67743375-af8e3f80-f9db-11e9-81f4-69e6f6bd15d8.png">

If the problem still persists, can you paste the full text from problem report into a comment?

**Comment by Code-DJ** [comment]
Hi @cormiertyshawn895 that didn't work either, so I deleted Aperture and redownloaded from the AppStore. Without opening it, ran through Retroactive and it worked correctly. Thanks for the awesome tool!!!
