### ISSUE TITLE
can't sign into iTunes on 12.6.5

### ISSUE THREAD

**Issue by pizzaonmychest** [cormiertyshawn895/Retroactive#209]
hello, im running 11.2.3 on a 2017 intel MacBook pro and with iTunes 12.6, the sign in window does not appear when attempting to sign in. i wasn't able to download any music from Apple Music when i was still signed in, and when i signed out and tried to go back in, it wouldn't work. nothing even appears. what is the fix?

**Comment by Terminal117** [comment]
Hi. I'm having a similar problem. i'm on the new MacBook Air M1 chip and and after dozens of trials installing iTunes with Retroactive, uninstalling both iTunes and Retroactive and re-install them again, I just can't make it work. When I try to install iTunes 12.9.5 I'm not able to run the app at all (see below) and when I install 12.6.5 I get Error 4013/4014 when I try to plug my iPhone 5S... Please help

Process:               iTunes [2221]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [2218]
Responsible:           bash [2218]
User ID:               501

Date/Time:             2021-03-19 04:39:15.682 +0000
OS Version:            macOS 11.2.3 (20D91)
Report Version:        12
Anonymous UUID:        65533ADC-E099-0038-D33B-AB15B40E24BD


Time Awake Since Boot: 4300 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x0000000307789ab0   pc: 0x00007ffdffe5ac0c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000


Binary images description not available


External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 52369
    thread_create: 0
    thread_set_state: 0

Model: MacBookAir10,1, BootROM 6723.81.1, proc 8:4:4 processors, 8 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: lp_ddr4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Dec 31 2020 21:39:03 version 18.20.222.20.7.8.104 FWID 01-1b2645bc
Bluetooth: Version 8.0.3d9, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
