### ISSUE TITLE
latest iTunes not launching on Monterey (MacBook Air M1)

### ISSUE THREAD

**Issue by ivabus** [cormiertyshawn895/Retroactive#232]
<img width="844" alt="Снимок экрана 2021-07-02 в 23 23 06" src="https://user-images.githubusercontent.com/71599788/124344689-76f52f00-dbdc-11eb-9c36-d7bb1275d357.png">

**Comment by bgrinstein** [comment]
Similar issue, probably related and probably because of BigSur+M1 combination (running on macmini M1,2020, Big Sur 11.4). It runs forever trying to unlock iTunes:
![Screen Shot 2021-07-06 at 3 03 08 PM](https://user-images.githubusercontent.com/13643434/124673998-c0f54380-de6e-11eb-81bc-7bb491da93a6.png)

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection when you install iTunes 12.9.5 on Mac computers with Apple Silicon.
