### ISSUE TITLE
iTunes quit unexpectedly.

### ISSUE THREAD

**Issue by PTechHD** [cormiertyshawn895/Retroactive#233]
Ive used retroactive many of times. I just purchased an M1 MacBook pro machine and installed iTunes using retroactive. I accidentally installed iTunes classic. iTunes did open without issue. I noticed that uninstalling was as easy as trashing the app. so I deleted the app and installed again, the default iTunes with dark mode. Well, now no matter what I do (including trying to install the classic version again) I get the iTunes quit unexpectedly message. here's the report

`Process:               iTunes [22349]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            iTunes
Version:               ???
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Translated)
Parent Process:        bash [22346]
Responsible:           bash [22346]
User ID:               501

Date/Time:             2021-07-05 13:46:50.882 -0500
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Anonymous UUID:        15****5C-****-41**-****-38606D811FF1

Sleep/Wake UUID:       D7****FF-F**0-****-8C**-E44*****9C73

Time Awake Since Boot: 290000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        Unknown

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace CODESIGNING, Code 0x1

kernel messages:

VM Regions Near 0 (cr2):
--> 
    mapped file                 104327000-106052000    [ 29.2M] r-x/rwx SM=COW  Object_id=78837c89

Backtrace not available

Unknown thread crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000000   x9: 0x0000000000000000  x10: 0x0000000000000000  x11: 0x0000000000000000
   x12: 0x0000000000000000  x13: 0x0000000000000000  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000000  x17: 0x0000000000000000  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x0000000000000000  x21: 0x0000000000000000  x22: 0x0000000000000000  x23: 0x0000000000000000
   x24: 0x0000000000000000  x25: 0x0000000000000000  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x0000000000000000   lr: 0x0000000000000000
    sp: 0x000000030e9f8a88   pc: 0x00007ffdffbc222c cpsr: 0x00000000
   far: 0x0000000000000000  esr: 0x00000000

Binary images description not available

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
Writable regions: Total=19.3M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=19.3M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                       10.5M        1 
VM_ALLOCATE (reserved)             568K        3         reserved VM address space (unallocated)
mapped file                        4.7G       11 
===========                     =======  ======= 
TOTAL                              4.8G       17 
TOTAL, minus reserved VM space     4.8G       17 

Model: MacBookPro17,1, BootROM 6723.120.36, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Apr 28 2021 19:53:33 version 18.50.40.7.7.8.119 FWID 01-e6894c69
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: iPhone, Ethernet, en7
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: iPhone
USB Device: USB 3.1 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
`

**Comment by Wizard-Mills** [comment]
I have this same issue. New M1 Mac. The older version of iTunes open, but the latest did not.

> "Exception Type: EXC_CRASH (Code Signature Invalid)
> Exception Codes: 0x0000000000000000, 0x0000000000000000
> Exception Note: EXC_CORPSE_NOTIFY
> Termination Reason: Namespace CODESIGNING, Code 0x1"

Tried to re-sign with codesign with no luck. Tried codesign including libraries; no luck.

In the end it works with protection off "csrutil disable".

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! [Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon.

If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

**Comment by Pika3pika** [comment]
Hi there, i have a similar issue, running ventura with open core legacy patcher on my intel 2012 MBP. I tried both newest and older versions of itunes, but i get the same: itunes quit unexpectedly error for each version of itunes. I've tried using R2, R1.9, R1.8, and different versions of itunes. 

Any advice?

Log: 
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               iTunes [23543]
Path:                  /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Identifier:            com.apple.iTunes
Version:               12.9.5 (12.9.5)
Build Info:            iTunes-1200012009005005~9
Code Type:             X86-64 (Native)
Parent Process:        Exited process [23540]
User ID:               501

Date/Time:             2023-04-02 14:35:59.8958 +0700
OS Version:            macOS 13.2 (22D49)
Report Version:        12
Anonymous UUID:        D4C5CD0D-62BC-5C9B-D235-7799999B9C87

Sleep/Wake UUID:       B4F90390-D42D-4F26-B9F0-492ECA635083

Time Awake Since Boot: 66000 seconds
Time Since Wake:       1329 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib
Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> /Applications/iTunes.app/Contents/MacOS/iTunes.app/Contents/MacOS/iTunes
Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@executable_path/../Frameworks/libgnsdk_dsp.3.06.1.dylib' (no such file), '/usr/lib/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	    0x7ff80e2b4b4a __abort_with_payload + 10
1   dyld                          	    0x7ff80e2cdd07 abort_with_payload_wrapper_internal + 82
2   dyld                          	    0x7ff80e2cdd39 abort_with_payload + 9
3   dyld                          	    0x7ff80e2551e1 dyld4::halt(char const*) + 375
4   dyld                          	    0x7ff80e252660 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4502
5   dyld                          	    0x7ff80e251281 start + 2289


Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000002000209  rbx: 0x0000000000000000  rcx: 0x00007ff7bb6953b8  rdx: 0x00007ff7bb695820
  rdi: 0x0000000000000006  rsi: 0x0000000000000001  rbp: 0x00007ff7bb695400  rsp: 0x00007ff7bb6953b8
   r8: 0x00007ff7bb695420   r9: 0x0000000000000000  r10: 0x0000000000000096  r11: 0x0000000000000246
  r12: 0x0000000000000096  r13: 0x00007ff7bb695820  r14: 0x0000000000000001  r15: 0x0000000000000006
  rip: 0x00007ff80e2b4b4a  rfl: 0x0000000000000246  cr2: 0x0000000106a33000
  
Logical CPU:     0
Error Code:      0x02000209 
Trap Number:     133


Binary Images:
    0x7ff80e24b000 -     0x7ff80e2dfcaf dyld (*) <270c4224-a38f-3a22-9ba9-95968f487738> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=197.4M resident=0K(0%) swapped_out_or_unallocated=197.4M(100%)
Writable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8192K        1 
VM_ALLOCATE                          8K        2 
__DATA                            3487K        3 
__DATA_CONST                        20K        1 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       167.6M        2 
__TEXT                            29.8M        2 
dyld private memory                512K        2 
shared memory                        4K        1 
===========                     =======  ======= 
TOTAL                            265.3M       16 



-----------
Full Report
-----------

{"app_name":"iTunes","timestamp":"2023-04-02 14:36:00.00 +0700","app_version":"12.9.5","slice_uuid":"91006ee5-c8c4-3a53-b7f7-69a3b2fd991a","build_version":"12.9.5","platform":1,"bundleID":"com.apple.iTunes","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.2 (22D49)","roots_installed":0,"name":"iTunes","incident_id":"3AE0BC71-9F3E-4990-A06D-7326FE7D59F5"}
{
  "uptime" : 66000,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro9,1",
  "coalitionID" : 8483,
  "osVersion" : {
    "train" : "macOS 13.2",
    "build" : "22D49",
    "releaseType" : "User"
  },
  "captureTime" : "2023-04-02 14:35:59.8958 +0700",
  "incident" : "3AE0BC71-9F3E-4990-A06D-7326FE7D59F5",
  "pid" : 23543,
  "cpuType" : "X86-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-04-02 14:35:59.8348 +0700",
  "procStartAbsTime" : 66641335513764,
  "procExitAbsTime" : 66641353397320,
  "procName" : "iTunes",
  "procPath" : "\/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes",
  "bundleInfo" : {"CFBundleShortVersionString":"12.9.5","CFBundleVersion":"12.9.5","CFBundleIdentifier":"com.apple.iTunes"},
  "buildInfo" : {"ProjectName":"iTunes","SourceVersion":"1200012009005005","BuildVersion":"9"},
  "storeInfo" : {"deviceIdentifierForVendor":"218BC82C-0687-54CE-B5D1-CD13805B7F3C","thirdParty":true},
  "parentProc" : "Exited process",
  "parentPid" : 23540,
  "coalitionName" : "com.launcher.iTunes",
  "crashReporterKey" : "D4C5CD0D-62BC-5C9B-D235-7799999B9C87",
  "responsiblePid" : 23540,
  "wakeTime" : 1329,
  "sleepWakeUUID" : "B4F90390-D42D-4F26-B9F0-492ECA635083",
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib","Referenced from: <91006EE5-C8C4-3A53-B7F7-69A3B2FD991A> \/Applications\/iTunes.app\/Contents\/MacOS\/iTunes.app\/Contents\/MacOS\/iTunes","Reason: tried: '\/System\/Volumes\/Preboot\/Cryptexes\/OS@executable_path\/..\/Frameworks\/libgnsdk_dsp.3.06.1.dylib' (no such file), '\/usr\/lib\/libgnsdk_dsp.3.06.1.dylib' (no such file, not in dyld cache), (security policy does not allow @ path expansion)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":601920,"threadState":{"r13":{"value":140701977892896},"rax":{"value":33554953},"rflags":{"value":582},"cpu":{"value":0},"r14":{"value":1},"rsi":{"value":1},"r8":{"value":140701977891872},"cr2":{"value":4406325248},"rdx":{"value":140701977892896},"r10":{"value":150},"r9":{"value":0},"r15":{"value":6},"rbx":{"value":0},"trap":{"value":133},"err":{"value":33554953},"r11":{"value":582},"rip":{"value":140703366335306,"matchesCrashFrame":1},"rbp":{"value":140701977891840},"rsp":{"value":140701977891768},"r12":{"value":150},"rcx":{"value":140701977891768},"flavor":"x86_THREAD_STATE","rdi":{"value":6}},"frames":[{"imageOffset":432970,"symbol":"__abort_with_payload","symbolLocation":10,"imageIndex":0},{"imageOffset":535815,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":82,"imageIndex":0},{"imageOffset":535865,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":0},{"imageOffset":41441,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":0},{"imageOffset":30304,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4502,"imageIndex":0},{"imageOffset":25217,"symbol":"start","symbolLocation":2289,"imageIndex":0}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 140703365902336,
    "size" : 609456,
    "uuid" : "270c4224-a38f-3a22-9ba9-95968f487738",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 140703365296128,
  "size" : 21474836480,
  "uuid" : "efc722b9-b3df-3d27-9a7b-c4acaf125abb"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=197.4M resident=0K(0%) swapped_out_or_unallocated=197.4M(100%)\nWritable regions: Total=9208K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=9208K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8192K        1 \nVM_ALLOCATE                          8K        2 \n__DATA                            3487K        3 \n__DATA_CONST                        20K        1 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       167.6M        2 \n__TEXT                            29.8M        2 \ndyld private memory                512K        2 \nshared memory                        4K        1 \n===========                     =======  ======= \nTOTAL                            265.3M       16 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    },
    {
      "rolloutId" : "61fd92db295c182621ececc3",
      "factorPackIds" : {

      },
      "deploymentId" : 240000346
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookPro9,1, BootROM 429.0.0.0.0, 4 processors, Quad-Core Intel Core i7, 2,6 GHz, 16 GB, SMC 2.1f170
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Graphics: NVIDIA GeForce GT 650M, NVIDIA GeForce GT 650M, PCIe, 1 GB
Display: Color LCD, 1440 x 900 (Widescreen eXtended Graphics Array Plus), Main, MirrorOff, Online
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x435438473353313630424D2E4D3136464544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x859B, 0x435438473353313630424D2E4D3136464544
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1766)
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: PNY CS1311 480GB SSD, 480,1 GB
Serial ATA Device: Samsung SSD 860 EVO 500GB, 500,11 GB
USB Device: USB30Bus
USB Device: USB20Bus
USB Device: hub_device
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB20Bus
USB Device: hub_device
USB Device: hub_device
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by Pika3pika** [comment]
Update: the classic version of itunes 11.4 works, but i can't use my library cause its made in 12.9.5.
Do i understand it correctly that SIP is blocking the newer version of itunes to open? Anyway to remove the itunes version number from the SIP list somewhere ?
