### ISSUE TITLE
Can't open Library File

### ISSUE THREAD

**Issue by Flying-Wellie** [cormiertyshawn895/Retroactive#240]
When trying to open a Aperture file I get this message. "Aperture cannot switch to the selected library because the file system of the library’s volume is not supported". Any ideas on how to overcome?

**Comment by GalaxyEmperor** [comment]
Do you have the Library on a external disk? What does Disk Utility say about that disk Type?

**Comment by jennifersqu** [comment]
I have a library issue also - I'm trying to open my previous library (from Mojave) after unlocking with Retroactive and get a message that the library needs upgrading and I have to open the library in iPhoto 9.4 to upgrade it. I obviously don't have iPhoto anymore and I would be wary of upgrading the library in case it broke it for good. Is this just because I'm trying to do this on Monterey? I have 1.7TB I don't want to lose and had to finally move from Mojave as I had other issues. Any advice appreciated! 

Intel iMac Monterey

**Comment by GalaxyEmperor** [comment]
Always make a copy of your library and use that copy for experiments. Can you give me some mor infos, what machine do you use (e.g. MacBook Air 2020 M1) what App you wanna use (Aperture?) how do you open the Picture Library (control click and choose the app?) what system exact version…

happy holidays

**Comment by jennifersqu** [comment]
Happy holidays Galaxy Emperor :-) Thank you for responding! 

Yes, copies are smart - just a little harder when it's a 1.7TB file. 

I'm on iMac 2017, 27 inch intel i7, newly running Monterey which just updated to version 12.1. I use Aperture, which incidentally works well with Retroactive for newly added photos (ie new library) which is great. I opened the library by holding option to select. I also tried opening from the app by switching library. 

As you didn't immediately say, of course that won't work, I'm wondering if it's because the library started life as an iPhoto library, back when Aperture and iPhoto talked and files were interchangeable. So it was an iPhoto album being used in Aperture (and not opened again in iPhoto for many years so I had forgotten it ever was). Which just gave me an idea... 

(Some time later...) Okay, it was my project files! Here's my work around. I am able to run Aperture and old library on an old iMac with Mojave. Then if I export a project as a new library and send it to the new iMac I can open the project and edit as normal, complete with existing version edits showing :-) The catch is I would end up with a couple of hundred libraries this way, but I can merge just the active projects to export as one library (slow, but possible) and split them again later... 

As you can tell, I am willing to go to some lengths to keep Aperture! I am thrilled Retrospective lets me do that.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
