### ISSUE TITLE
App request: iWeb

### ISSUE THREAD

**Issue by upintheairsheep** [cormiertyshawn895/Retroactive#278]
iWeb w looks amazing and they discontinued it because there was no hosting on iCloud.

**Comment by ylluminate** [comment]
Yes, very sad. It was nice. Apple [pulled a Google](https://killedbygoogle.com/) on this one. Closest alternative I've found is [EverWeb](https://www.everwebapp.com/) and it's pretty robust.

**Comment by cormiertyshawn895** [comment]
iWeb is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.

You can use Parallels Desktop, VMware Fusion, or UTM to install macOS Mojave and run iWeb’09 there, but because there isn’t OpenGL acceleration, you won’t be able to see live previews, so it’s not very practical.

If you install iWeb’08 on OS X Leopard under Parallels Desktop, VMware Fusion, or UTM, you can open Finder > Applications, right click on the iWeb app and choose "Show Package Contents", then browse to `/Contents/Resources/` and open the `Defaults.plist` in TextEdit.

Find the lines:
```
<key>SFRAcceleratedCanvas</key>
<true/>
```

and change it to:
```
<key>SFRAcceleratedCanvas</key>
<false/>
```

This should get you a usable iWeb’08 with live preview.

**Comment by upintheairsheep** [comment]
> iWeb is a 32-bit app, which requires virtualization to run on macOS Catalina or later. Implementing a virtual machine is out of scope for Retroactive.
> 
> You can use Parallels Desktop, VMware Fusion, or UTM to install macOS Mojave and run iWeb’09 there, but because there isn’t OpenGL acceleration, you won’t be able to see live previews, so it’s not very practical.
> 
> If you install iWeb’08 on OS X Leopard under Parallels Desktop, VMware Fusion, or UTM, you can open Finder > Applications, right click on the iWeb app and choose "Show Package Contents", then browse to `/Contents/Resources/` and open the `Defaults.plist` in TextEdit.
> 
> Find the lines:
> 
> ```
> <key>SFRAcceleratedCanvas</key>
> <true/>
> ```
> 
> and change it to:
> 
> ```
> <key>SFRAcceleratedCanvas</key>
> <false/>
> ```
> 
> This should get you a usable iWeb’08 with live preview.

So how did you get Aperture and older iTunes versions running
