### ISSUE TITLE
Problems with Monterey 12.5.1

### ISSUE THREAD

**Issue by danielFFM** [cormiertyshawn895/Retroactive#291]
Hello together,

Today I bought a new MacBook Pro (16“,2021) - Chip: Apple M1 Max
OS: Monterey 12.5.1

App: Retroactive 1-3.9 (1.9)

Why do I need iTunes?
Primarily to transfer music to the playlists on the IPod. I cannot display the playlists on the iPod in the Music app.

Results - Install iTunes:

1. iTunes 12.9.5
iTunes quit unexpectedly

Exception Type:  EXC_CRASH (SIGKILL (Code Signature Invalid))
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 1

2. iTunes 12.6.5
Starts - but then the first message: An unknown error has occurred (-42408)
- ipod is not recognised
- iPhone (13 Pro Max - iOS 15.6.1) : iTunes Cannot read the content on the iPhone…..
- 
3. iTunes 11.4
Starts…but
- iPod: needs higher iTunes Version
- iPhone (13 Pro Max - iOS 15.6.1) : iTunes Cannot read the content on the iPhone…..

So..I really need help!

thanks in advance and best regards

Daniel

**Comment by cormiertyshawn895** [comment]
Thanks for reporting! 

[Retroactive 2.0](https://github.com/cormiertyshawn895/Retroactive/releases/tag/2.0) now provides instructions to turn off System Integrity Protection before installing iTunes 12.9.5 on Mac computers with Apple Silicon. If you would like to keep System Integrity Protection enabled, you can choose to install an older version of iTunes.

With that said, syncing with iPhone, iPad, and iPod through iTunes don’t work with macOS Monterey due to underlying changes in macOS. A trick you can use is to locally create a playlist in the Music app, then drag the entire playlist into your device. This will let you copy the entire playlist to the device.
