### ISSUE TITLE
Double clicking mp3 issue

### ISSUE THREAD

**Issue by Tonym69** [cormiertyshawn895/Retroactive#310]
Double clicking mp3 only adds it to iTunes when iTunes is closed first. If iTunes is open then a duplicate dock icon appears but track doesn't add.

iTunes 12.9.5, Retroactive 2.0, running on Big Sur, 

Is there any way around this?

**Comment by DabeDotCom** [comment]
FTR, I noticed the same thing...  When it's already running:

```
open -a /Applications/iTunes.app CoolSong.mp3
```

... only tells "iTunes" to activate; it doesn't actually **Open/Add** the file.

I was hoping the launcher/wrapper app might pass the file(s) to the script as arguments (`$@`) but no dice.  :-(

Even stranger, after updating the file association for all MP3s in Finder, `open CoolFile.mp3` by itself doesn't even call the shell wrapper ***at all***...  It just creates a NEW iTunes icon in the dock, which bounces forever until you "Force Quit" it — maybe because the launcher app doesn't "claim" the `public.mp3` UTI, et al?  «shrug»

(I have to admit, Apple's whole application startup process feels like black magic to me; what was so wrong with `char *argv[]` ?!?!)

**Comment by DabeDotCom** [comment]
PS: Now I'm thinking of writing an Automator / Applescript / [Platypus](https://sveinbjorn.org/platypus) wrapper app ***AROUND*** the Retroactive `iTunes.app` wrapper(!)

*"If it's stupid, but it works, it isn't stupid!"*  «grin»

**Comment by shishkabibal** [comment]
@DabeDotCom Did you ever figure out a solution for this? This has bugged me for the longest time. This isn't even the only open issue regarding this problem, here's one from 2020 bumped in 2022: https://github.com/cormiertyshawn895/Retroactive/issues/111. Is this just an issue that other people have?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
