### ISSUE TITLE
Nothing but issues with iTunes on Ventura 13.2.1

### ISSUE THREAD

**Issue by scatteredfrog** [cormiertyshawn895/Retroactive#355]
I installed Retroactive on a brand new M2 MacBookPro. Model: Mac14,7

Any version of iTunes, the software itself installs, opens, and plays and manages music, podcasts, etc.

However,

1) Upon startup, I get the infamous "An unknown error occurred (-42408)" modal.

2) When I try to sign in or authorize, three modals stacked on top of each other occur, each claiming "There was a temporary problem completing your request. An unknown error occurred." The two modals on top tell me error 9039, and the one on bottom says 11571. In the end, I'm not signed in.

3) iTunes does not see that there's an iPod connected. Actual macOS recognizes it, but not iTunes. It's as if nothing ever plugged in. I tried "killall AMPDevicesAgent" to no avail.

I've tried uninstalling Retroactive and even reinstalling Ventura. Also tried migrating from a backup of my older MBP (Intel running Monterey 12.6.3). I also have an iMac (also Intel) running Ventura 13.2.1. Both run iTunes via Retroactive flawlessly.

So first glance says that it's the Apple silicon that something does not like.

**Comment by Woolwit** [comment]
I have an M1 Mac Mini, Monterey 12.6, Retroactive 1.9, and iTunes 11.4 running flawlessly. 
I think I'd buy another computer before risking losing iTunes, considering how much I depend on it for podcasts, and how much I hate Apple Podcasts/Music.
If anyone in a similar situation reading this can confirm they were able to update to Ventura please share in here.

**Comment by fastiuk** [comment]
Try to install an older version of iTunes.
I installed version 12.6.5 and it is working for me

**UPD: No it doesn't:(**

**Comment by DougCline** [comment]
I have a Mac mini m2 Pro running Ventura 13.2.1. I have both Music 1.3.3.2 and iTunes 12.9.5.5. When I start iTunes I get the (-42408) error message and if I try to sign in to my music account I get try again error messages 9309 and 11571. I have made my iTunes the primary account with a consolidated library. As all of my music is cd's I own and have ripped into iTunes this works for me other than no genius. The Music also works and I do not consolidate files in Music. When I bring in a new cd, I bring it into iTunes and then open Music and "Add to Library" the cd directly from the iTunes library. A little convoluted but it works for me to preserve the iTunes look and feel as well as access to multiple artwork attached to the album/songs.

**Comment by fevers55** [comment]
Two weeks ago I downloaded Retroactive to a MacBook Air Intel 1.8 running Ventura 13.2.1. I installed iTunes 12.9.5. All went smoothly, as advertised.

A couple of days ago I did the same with a new Mac Mini M2 running Ventura 13.3.1, and installed iTunes 12.9.5. With this install I ran into issues described above: the 42408 error when the library loads, and multiple errors (9039 and 11571) when trying to sign in and trying to authenticate.

An additional, perhaps related, issue is my Apple TV recognizes the library from the MacBook Air, but cannot see the one on the Mini (with the same settings and connections as the Air). Library sharing and Home Sharing are both switched on in each.

PS to DougCline’s comment above: wanting to display different intra-album artwork by song on my Apple TV is exactly why I went the Retroactive route. I must not be smart enough to understand why embedded art in each individual track can’t be displayed. :)

**Comment by OmskInfo** [comment]
I'm also having this same problem. Error -42408 when iTunes first launches on my M2 MacBook Air with Ventura 13.3.1. After clearing that dialog, I try to sign in to my iTunes Account. The dialog comes up, I input my e-mail and password. But then I get a bunch of errors. 9039 and 11571. It doesn't ultimately sign in, so I can't access my music in the cloud. :-(

iTunes works fine on my Intel MacBook Pro running Big Sur, thankfully.

**Comment by dhnyny** [comment]
I've got iTunes 12.6.5.3 running on a new 15" MacBook Air M2. I get the -42408 error once or twice on launch but that doesn't seem consequential. Everything that I want to do with iTunes seems to work fine except it won't communicate with my new iPhone SE. If I can't get it to sync with my iPhone, I think it's not going to be viable for me. Has anyone managed to get syncing to work on a non-Intel Mac?

**Comment by don-911** [comment]
I'm running iTunes 12.9.5.5 on an M2 Macbook Pro (Mac14,6) with Ventura 13.4.1. With SIP enabled, iTunes won't launch. But with SIP disabled, I get the same errors as the OP scatteredfrog including my 7th gen iPod not mounting. However, the 5.5 gen iPod does mount and sync. So that's interesting. Apart from iPod mounting issue, and the -42408 error at startup and the 9039 and 11571 errors when trying to log in to the store or Authenticate, most other things seem to be working fine. I can't subscribe to iPods normally, but if I first get one episode by clicking 'Get' I can then subscribe once the podcast has been added to the list. And after that, subscribed Podcasts update normally.

I recently bought a new M2 MBP with a 4TB SSD in order to finally move my iTunes world from a 2018 Intel Mac mini to Apple silicon. So I'm quite sad to see that iTunes doesn't work as well on Apple Silicon as it does on Intel. Does anyone know if cormiertyshawn895 would be able to fix these issues with an update or if they are unfixable (iPod classic mount/sync, SIP enabled, store log-in)? By the way, is there a way to contact cormiertyshawn895 to ask?

Other options I have been playing around with include (reluctantly) moving my iTunes music to the Music.app and running iTunes only for Podcasts in a virtual machine. I frequently convert Youtube videos to audio and then add them to iTunes Podcasts so I can listen to them on my iPod Classic, and the new Podcasts app can't import audio files, only download official podcasts. For anyone interested, here's what I have found in my trials:

VMware Fusion on Apple Silicon doesn't support macOS VMs yet, and Parallels can only install the same macOS version you are running as the host OS. Both platforms only support Windows 11 VMs, not Windows 10.

Installing iTunes in a Ventura VM in Parallels on M2, I get the same -42408 error on startup, but then can't open the store at all. Nothing happens when I click the button. Also no way of connecting USB devices like iPods to the VM. This will probably change once Parallels macOS VM is out of 'beta', but will probably have the same iPod mounting issues as the Mac itself.

Installing iTunes 12.10.11.2 for PC on a Win 11 VM in Parallels on M2, everything seems to work including iPod sync. Subscribe to Podcasts OK if ‘Get’ one episode first and then subscribe. Otherwise, you get a “There is a temporary problem completing your request” error. However, if you upgrade to the latest version of iTunes, 12.12.9.4, then you get this error: "This iPod cannot be used because it is not supported on this version of Windows". So for people choosing this option, stay on iTunes 12.10.11.2.

But obviously, the dream scenario would be that iTunes 12.9.5.5 ran as well on M2 as on Intel. Hopefully, cormiertyshawn895 will be able to fix this with an update.

**Comment by don-911** [comment]
> I have an M1 Mac Mini, Monterey 12.6, Retroactive 1.9, and iTunes 11.4 running flawlessly.

@Woolwit Are you still running this config successfully or have you upgraded anything? I tried iTunes 11.4 on Ventura 13.4 today and it crashed when I tried to sync an iPod Classic (both 7th and 5.5 gen). But at least both mounted. Have you synced an iPod Classic on your system? I also tried 12.6.5 and 7th gen iPod did not mount but 5.5 gen did.

**Comment by Woolwit** [comment]
@don-911 Yes, I'm leaving it just as is until I find a workaround. I run an iPod Classic as well with no issues, but mainly I'm syncing last gen Shuffles. That said, I'm not logging in to Apple for anything else either, so there may be some issues I haven't run into. BTW I use an app called Poddr for search. The result gives you both the show website and the feed RSS url.

**Comment by scatteredfrog** [comment]
Update: still getting the exact same problems with Retroactive 2.1, and currently on Sonoma 14.4, same hardware as in original post.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
