### ISSUE TITLE
Since retroactive aperture is exporting hidden files and folders

### ISSUE THREAD

**Issue by rudiwells** [cormiertyshawn895/Retroactive#36]
Rebooting seems to make these folders and files appear, this happens with exporting to any drive or desktop. But only 75% of the time.
Happens when exporting multiple files with or without an export preset

**Comment by cormiertyshawn895** [comment]
Do these hidden exported files show up in Finder if you press `command + shift + . (period key)`? This should reveal all hidden files. (Press the same key command again to hide hidden files.)

If they don't show up, what happens if you click on the Apple logo in the menu bar, choose "Force Quit...", locate Finder in the list, and click "Relaunch"? Do exported files show up then?

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
