### ISSUE TITLE
iTunes 12.9 cannot read contents of iPhone or iPad

### ISSUE THREAD

**Issue by krzajac** [cormiertyshawn895/Retroactive#400]
like the title says, iTunes cannot read my devices.
<img width="1277" alt="Screenshot 2023-11-09 at 12 57 36 PM" src="https://github.com/cormiertyshawn895/Retroactive/assets/150380011/b9ef21ee-01fa-48e6-a6c2-b364660ceb24">

**Comment by RedTartan04** [comment]
Which macOS Version? Can you access them in Finder?

**Comment by krzajac** [comment]
MacOS Ventura

**Comment by count0x30** [comment]
I'm on Ventura, and iTunes 12.9 can sync with my iPhone and iPod nano, though not my shuffle.  I don't have an iPad to test.  Maybe check out the section "Syncing with a device" in the Retroactive Readme.

I'm wondering if anyone has experience with syncing to devices on Sonoma, because that's what's keeping me from doing an upgrade.

**Comment by tertiumsquid** [comment]
I get the same error on Monterey, doesn't matter what version of iTunes I use.  iTunes can sync to all my iPods though.

Monterey 12.7.1, Mac Mini M1

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
