### ISSUE TITLE
ITunes No Longer Working

### ISSUE THREAD

**Issue by TheLydiot** [cormiertyshawn895/Retroactive#408]
Updated from Catalina, where iTunes (all versions) run perfectly, to Monterey. iTunes opened once since update. Computer crashed and restarted, and since then iTunes window does not open at all. Tried deleting Retroactive and iTunes with app cleaner, and then reinstalling, trying different versions, and none work. This is all with Retroactive 2.0. Please advise.

**Comment by ylluminate** [comment]
Switch to Swinsian 3.0 Preview 13 (595). You won't be disappointed. I have changed after Retroactive's developer made the suggestion to move away from it due to increasing headaches and I'm super pleased with Swinsian and the attentiveness of its developer. I feel like I'm back to what iTunes used to be now on a large music library (it imported my iTunes library without a hitch).

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
