### ISSUE TITLE
MacOS Mojave10.14.6 can install iTunes12.6.5?

### ISSUE THREAD

**Issue by BitionSong** [cormiertyshawn895/Retroactive#60]
I am many times all not line, is not support?

![2020-03-21 22 22 06](https://user-images.githubusercontent.com/45449184/77228457-9bcdba80-6bc2-11ea-89b2-6f723cde876d.jpg)

![2020-03-21 22 23 58](https://user-images.githubusercontent.com/45449184/77228465-ad16c700-6bc2-11ea-97ab-14ea4af43082.jpg)

**Comment by dowsmith** [comment]
I have a similar problem: I'm running Mojave, and want to unlock/fix iTunes.
However,  Aperture, iPhoto and iTunes are all greyed out.

**Comment by walterdavis** [comment]
If you're running Mojave, you don't need to do anything to get Aperture (and probably the others) to work. Mojave is the last version of MacOS where they run without any help.

Walter

**Comment by cormiertyshawn895** [comment]
As of April 2020, iTunes 12.6.5 no longer supports downloading iOS apps on all macOS versions. This is a server side change, and can't be fixed by apps like Retroactive.

Since iTunes 12.6.5 doesn't support downloading iOS apps anyways, you should just use iTunes 12.9.5, which is built into macOS Mojave.

**Comment by dowsmith** [comment]
There were other benefits to iTunes 12.6.5 - it allowed re-arrangement of home-screens via the mac, which was much easier than trying to do it on the phone...
