### ISSUE TITLE
Custom keyboard shortcuts not working on iTunes

### ISSUE THREAD

**Issue by gioncoltrein** [cormiertyshawn895/Retroactive#64]
I tried to set some keyboard shortcuts for iTunes, through System Preferences > Keyboard > Shortcuts, as I have always done with iTunes, but they don't work with Retroactive iTunes. For example, if I want to show the tracks of a playlist ”as Songs” (menu View->View As->Songs), I create the following keyboard shortcut: Shift+Command+S. But after creating it, iTunes doesn't take it… How can this be fixed?

![image](https://user-images.githubusercontent.com/62849599/77855998-8e34b800-71f4-11ea-8527-b942431db403.png)

![image](https://user-images.githubusercontent.com/62849599/77856009-9bea3d80-71f4-11ea-8b23-783eeedbd27d.png)

**Comment by cormiertyshawn895** [comment]
You need to add the keyboard shortcut for "All Applications" instead of iTunes.
<img width="780" alt="all-apps" src="https://user-images.githubusercontent.com/57056759/77884448-ee8a2080-7219-11ea-8709-defeec66dfd9.png">

<img width="652" alt="menu" src="https://user-images.githubusercontent.com/57056759/77884424-e205c800-7219-11ea-9f1b-e65bc23f47b4.png">
