### ISSUE TITLE
Aperture custom key commands not applied after app launch

### ISSUE THREAD

**Issue by josebrito** [cormiertyshawn895/Retroactive#71]
Hi,

I've noticed that every time I launch Aperture, my custom key commands setup is not selected. Also, the custom key command set gets renamed to `<original name> 2` every time I launch the app:

<img width="461" alt="Screenshot 2020-04-13 at 19 31 38" src="https://user-images.githubusercontent.com/12597782/79148750-ef948380-7dbd-11ea-8031-d0e1b22df094.png">

I'm using Catalina in a 2017 Macbook Pro. This issue does not happen in my legacy machine where Aperture is perfectly supported. Not saying that Retroactive has anything to do with this issue, but I guess it made sense to report it here. :)

Last, but most importantly, **THANK YOU FOR THIS APP**!!

**Comment by cormiertyshawn895** [comment]
Thank you for your kind words about the Retroactive app, and for flagging this. It must be maddening to see your custom command set automatically renamed and not persist across launches. 

Good news! This has been fixed with [the latest version of Retroactive (1.6, Build 50)](https://github.com/cormiertyshawn895/Retroactive/releases). If you are already affected by this, follow these steps:

- Quit Aperture
- Open Finder
- Go > Go to Folder... > `~/Library/Application Support/Aperture/Command Sets` > Go
- Rename `MY_KEY_COMMANDS 2 2` back into `MY_KEY_COMMANDS`
- [Download the latest version of Retroactive](https://github.com/cormiertyshawn895/Retroactive/releases), choose Aperture, and unlock it again
- Open Aperture
- Aperture > Commands > choose `MY_KEY_COMMANDS`
- Quit Aperture and open it again

`MY_KEY_COMMANDS` should remain selected, and will no longer be automatically renamed!

**Comment by josebrito** [comment]
@cormiertyshawn895 it worked! It's a huge time saver, thanks a lot!! 🥇
