### ISSUE TITLE
[Discussion] Adobe CS6?

### ISSUE THREAD

**Issue by lochlainn** [cormiertyshawn895/Retroactive#78]
I realize this is out of the scope of the current project, but I figured this repo's community might be the best people to ask.

Is there any possibility/feasibility for Adobe CS6 (particularly Photoshop) to be ported to Catalina? What would that process even look like?

If I wanted to start researching this, where would be a good place to start?

**Comment by cormiertyshawn895** [comment]
> Is there any possibility/feasibility for Adobe CS6 (particularly Photoshop) to be ported to Catalina? What would that process even look like?

Photoshop CS6 itself is already 64-bit and can work on macOS Catalina. But because the Photoshop CS6 installer and licensing manager are 32-bit, macOS Catalina blocks Photoshop CS6 from launching with a system-wide compatibility check.

If you have already installed and activated Photoshop CS6 with a genuine license before upgrading to macOS Catalina, [you can follow one of the many tutorials on YouTube](https://www.youtube.com/results?search_query=Photoshop+CS6+Catalina) to skip the compatibility check and use it as normal.
