### ISSUE TITLE
App Request: DVD Studio Pro

### ISSUE THREAD

**Issue by davidchai75** [cormiertyshawn895/Retroactive#87]
There is nothing like this app available anymore, but its still useful...

**Comment by xtreme1690** [comment]
> There is nothing like this app available anymore, but its still useful...

It would be awesome if DVD Studio Pro could be made to work, its part of the Final Cut Studio 3 suite and such a shame that since High Sierra it was killed off...

Edit (19th May 2020) : I just want to add i tried forcing this to run, changed the CFBundleIdentifier in info.plist , manually installed BrowserKit and ProKit frameworks and i thought all was good when the program seemed to run, asked me for a serial (which i have). After that though it dies out. Crashes either with SEGMENTATION FAULT: 11 in terminal or it brings up an error box with COREFOUNDATIONERR:UNKWN (Or something along those lines).  So would be really cool if we can get this working with Retroactive!

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
