### ISSUE TITLE
Applescript support

### ISSUE THREAD

**Issue by shansell** [cormiertyshawn895/Retroactive#90]
Is it possible for iTunes to support applescript? Currently there isn't an iTunes dictionary exposed, so I assume it won't respond to scripts.

**Comment by duncanbrook** [comment]
+1 million for this request.

I'm so happy to have iTunes back on Catalina — thank you! — but the absent AppleScript support unfortunately means more lost functionality than "you can't use any of [Doug's Scripts](https://dougscripts.com/itunes/index.php)."

AppleScript is how e.g. [Neptunes](https://micropixels.software/neptunes), [SizzlingKeys](http://www.yellowmug.com/sk4it/) and most (all?) other controller utilities and/or [last.fm](https://www.last.fm/) scrobblers interact with iTunes.  Without AppleScript support, none of them can see zombie iTunes on Catalina.

I've been using Doug's scripts and a certain set of external keyboard shortcuts to control iTunes since 2001, plus scrobbling my music plays to last.fm since 2005, so I miss all of this functionality terribly!

**Comment by autli** [comment]
+1 without Apple Script support iTunes is not complete (tested with 12.9.5 on Big Sur 11.1).
Apart from this Retroactive works well, thank you!

**Comment by peterbuga** [comment]
I have applescripts working just fine for me, custom scripts written/improved over years iTunes 12.9.5.5 + Big Sur 11.5.2 currently

```
tell application "iTunes"
	set mySelection to every track of playlist "random"
.....
end tell
```

@duncanbrook regarding Neptunes and other apps alike, I've been able to change/recompile them to work with iTunes check here https://github.com/cormiertyshawn895/Retroactive/issues/122
other mentionable apps that I've changed are SpotMenu, iTunes Volume Control, Song Rating. 

let me know if this helps anyone 🤷‍♂️ i could start some forks for these and publish them, I'm not an objective-c/swift developer but I try to do minimal changes in order to make things work for my personal use

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
