### ISSUE TITLE
Still on Mojave & Aperture = getting Unsupp. Format message

### ISSUE THREAD

**Issue by VictoriaJZ** [cormiertyshawn895/Retroactive#94]
I did repair Database etc. and also Reprocess several times, no dice.  Some pics come in trashed and in colors, some with the black w/white icon, some are 0 bytes and some remain 10mb.  I've also exported the photos and reimported them, same thing.  Have not tried Retroactive [had not known about it before and am loathe to move to Catalina still]

<img width="656" alt="Screen Shot 2020-05-27 at 7 57 49 AM" src="https://user-images.githubusercontent.com/66019600/83029781-ae1c0880-9ff8-11ea-80c5-40a87f2598de.png">

**Comment by cormiertyshawn895** [comment]
Since you are running Aperture on macOS Mojave, this is not a problem with Retroactive. It's probably a general compatibility issue between macOS system frameworks and the image format your camera uses. 

Can you send me one or two sample photo that are corrupted to cormiertyshawn895@gmail.com? That way, I can try to look at what went wrong.

**Comment by cormiertyshawn895** [comment]
Retroactive has been discontinued, and does not support macOS Sequoia or later. You should transition from Retroactive to a wide range of supported apps, many of which are built into macOS or free to download. [Learn how to transition from Retroactive to supported apps](https://github.com/cormiertyshawn895/Retroactive/blob/master/TRANSITION.md).
